import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import Header from '@/components/header'
import Footer from '@/components/footer'
import Hero from '@/components/hero'
import Content from '@/components/content'
import Community from '@/components/community'
import Contact from '@/components/contact'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Header />
        <Hero />
        <Content />
        <Community />
        {children}
        <Contact />
        <Footer />
        </body>
    </html>
  )
}
